### ISSUE TITLE
incorrect bundle is generated when `require(<json file>)` is included

### ISSUE THREAD

**Issue by camc314** [rolldown/rolldown#1446]
consider the following:

```ts
// index.js
var codes = require('./codes.json')

console.log(codes)
```

`codes.json`
```json
{
    "foo": "bar"
}
```

The expected runtime output is

```
$ node index.js
{
    "foo": "bar"
}
```

however the actual runtime output is 
```
$ node ./dist/entry.js
{ default: [Getter], foo: [Getter] }
```

Bundle:
```js
//#region rolldown:runtime
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esmMin = (fn, res) => () => (fn && (res = fn(fn = 0)), res);
var __export = (target, all) => {
	for (var name in all) __defProp(target, name, {
		get: all[name],
		enumerable: true
	});
};
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === 'object' || typeof from === 'function') for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
		key = keys[i];
		if (!__hasOwnProp.call(to, key) && key !== except) __defProp(to, key, {
			get: ((k) => from[k]).bind(null, key),
			enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
		});
	}
	return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, '__esModule', {value: true}), mod);

//#endregion
//#region codes.json
var codes_ns, foo, codes_default;
var init_codes = __esmMin(() => {
	codes_ns = {};
	__export(codes_ns, {
		default: () => codes_default,
		foo: () => foo
	});
	foo = 'bar';
	codes_default = {foo};
});

//#endregion
//#region index.ts
var codes = (init_codes(), __toCommonJS(codes_ns));
console.log(codes);

//#endregion
```

related code:

https://github.com/rolldown/rolldown/blob/5d9811f4996ed7872b1a0365c1ab9f5c8c832798/crates/rolldown_loader_utils/src/json_to_esm.rs#L6-L41

**Comment by camc314** [comment]
@hyf0 i am happy to (try) to fix this, am i correct in thinking that we just need to rework the `json_to_esm` function?

**Comment by hyf0** [comment]
> @hyf0 i am happy to (try) to fix this, am i correct in thinking that we just need to rework the `json_to_esm` function?

Not sure. The current behavior is right while you are using `import ... from '...'`. I would more consider this as a problem of `require` an esm module.

**Comment by hyf0** [comment]
Just looked at some specs:
- nodejs doesn't support named import on json modules https://github.com/nodejs/modules/issues/255
- https://github.com/whatwg/html/issues/4315 follows this behavior too.

While supporting named import on json modules is friendly to treeshaking, but so far rolldown's primary goal should be following the spec.

Also it's because that it's hard to ensure that `import ... from '....json'` and `require('....json')` have the same behavior as nodejs while supporting named import on json modules.

So I'm gonna revert this feature and modify `json_to_esm`.

Esbuild just simply did `module.exports = ...`, we gonna follows that.

> Also it's because that it's hard to ensure that `import ... from '....json'` and `require('....json')` have the same behavior as nodejs while supporting named import on json modules.

Once we figure out how to support named imports on json modules with compatibility of nodejs's behavior, we will bring this feature back.

**Comment by hyf0** [comment]
@camc314 you are very welcome to do it. I guess the function should be renamed to `json_to_cjs`.

**Comment by hyf0** [comment]
I just thought about it how to solve this problem. We could keep this feature and also fix this issue.
