### ISSUE TITLE
[Bug]: no sourcemap generated or sourcemap generated unnecessarily

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#2077]
### Reproduction link or steps

I'm testing Rolldown in https://github.com/oxc-project/monitor-oxc/tree/rolldown

### What is expected?

Either:
* sourcemap generated
* no code path to sourcemap generation

### What is actually happening?

With the default config 

```
import { defineConfig } from 'rolldown'

export default defineConfig({
  input: 'src/main.test.mjs',
  external: [
    "fsevents",
    "@swc/core"
  ],
  output: {
    format: 'es',
  },
})
```

I'm seeing sourcemap code getting called, but I see no sourcemap generated in dist nor inlined in the bundled files.

![image](https://github.com/user-attachments/assets/8b36031e-f033-4f9f-b6a6-1fa79d7c749b)

### System Info

```Shell
None
```

**Comment by shulaoda** [comment]
I will try it. 👀

**Comment by 7086cmd** [comment]
It appears that the `concat_source` is shared in both enabled and disabled states. This may be due to the placement of the `ConcatSource` within the `rolldown_sourcemap`.

The location of the triggering sourcemap:

https://github.com/rolldown/rolldown/blob/d023f2f95d604a3ab2ce0d627795fc8a3b77bd99/crates/rolldown/src/utils/render_ecma_module.rs#L27-L50

**Comment by 7086cmd** [comment]
It appears that the `concat_source` is shared in both enabled and disabled states. This may be due to the placement of the `ConcatSource` within the `rolldown_sourcemap`.

The location of the triggering sourcemap:

https://github.com/rolldown/rolldown/blob/d023f2f95d604a3ab2ce0d627795fc8a3b77bd99/crates/rolldown/src/utils/render_ecma_module.rs#L27-L50

In my opinion, setting the `sourcemap` attribute to `hidden` will not trigger any events related to source map.

- The `sourcemap_builder` will be set to `None` in the `content_and_sourcemap` dictionary;
- The `sourcemap` function will return `None` in the `RawSource` class, while the `SourceMapSource` class will only be invoked in sourcemap-enabled contexts (as demonstrated in the code above). Consequently, the `enable_sourcemap` attribute will not be set to `true` if the sourcemap is hidden.

**Comment by Boshen** [comment]
> In my opinion, setting the sourcemap attribute to hidden will not trigger any events related to source map.

Is this a statement or a proposed fix?

**Comment by RegirX** [comment]
Ethan: I would prefer it phrased as a statement. The `sourcemap` keyword is essentially just about the placement of `concat_source`; in my opinion, it doesn't really matter.

*Ethan is unable to log in to GitHub on campus due to 2FA restrictions.*

**Comment by underfin** [comment]
@Boshen The behavior of `ConcatSource#content_and_sourcemap`  is simliar to  the sourcemap of `oxc::CodeGenerator`, if the `sourcemap` is disabled, it will not calculate related sourcemap only return code. I think it is expected at here.

**Comment by Boshen** [comment]
> I think it is expected at here.

Shall we close this issue as won't fix, or is there something to be fixed?

**Comment by 7086cmd** [comment]
I would suppose it won't be necessary to fix right now. I think when we are refactoring the ConcatSource struct, we can place it to a better place.

**Comment by 7086cmd** [comment]
I would suppose it won't be necessary to fix right now. I think when we are refactoring the ConcatSource struct, we can place it to a better place.
