### ISSUE TITLE
[Bug]: internal resolver does not normalize `\\` with `/`

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2303]
### Reproduction link or steps

1. Download https://stackblitz.com/edit/github-6jajke-ay1vqe?file=README.md on Windows machine
2. Run `npm run build` and `npm run build:vite`
3. See the output difference

(An example output is written in README.md)

### What is expected?

Rolldown behaves the same with Vite (normalizes `\\` to `/`) or has a option to do that.

### What is actually happening?

Rolldown does not normalize `\\` to `/`.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@351d2c7 => 0.13.2
```

### Any additional comments?

See https://vitejs.dev/guide/api-plugin.html#path-normalization.

Faced this while trying rolldown with Vite.

**Comment by hyf0** [comment]
Some notes:
- rolldown now should does normalize on path to make sure `/./x.js` and `/x.js` is the same module.
- rolldown doesn't handle transforming `//` to `\` specially so far.

**Comment by IWANABETHATGUY** [comment]
We could normalize logic on the vite side, if we found this has a performance bottleneck, then we could write a temp native plugin to do that.

**Comment by sapphi-red** [comment]
If rolldown does not do this normalization, Vite needs to add a plugin that catches all resolveId request:
```js
const plugin = {
  name: 'normalizer',
  resolveId(id, importer, opts) {
    // this functionality is not exposed,
    // `this.resolve` will call other plugins but here we only want to use the internal resolver
    // maybe it's same with oxc-resolver?
    const result = resolveUsingRolldownInternalResolver(id, importer, opts)
    return normalizeSlash(result)
  }
}
```
But I guess this could be slower than the following plugin since the plugin above goes JS and rust back and forth.
```js
const plugin = {
  name: 'normalizer',
  resolveId(id, importer, opts) {
    const result = path.resolve(path.dirname(importer), id)
    return normalizeSlash(result)
  }
}
```
Then, Vite cannot use the internal resolver even partially for relative ids.

Maybe I'm missing something.

**Comment by hyf0** [comment]
We could normalized `//` to `\` in rolldown, since normalization would be done anyway.

**Comment by hyf0** [comment]
More notes:

> This only processed the input. #2303 is about normalizing all paths from `\\` to `/`.
> 
> We also need to define the behavior of normalizing `\\` to `/`. When does `\\` would be treated as itself rather than a path separator? I'm ok with just converting every `\\` to `/`, just need to make sure it's expected.

https://github.com/rolldown/rolldown/pull/2363#issuecomment-2386261757

**Comment by hyf0** [comment]
After going through https://vitejs.dev/guide/api-plugin.html#path-normalization, I think the final behavior should be

## Contexts:

- In most cases, rolldown just pass `specifier` to `oxc-resolver` and pass the return value directly to `resolve_id` hook.
- `oxc-resolver` return found file path. And `\\` is a valid path separator in windows, so if there is `\\` shown up is depended by the running OS.

## Behaviors:

- Rolldown doesn't have any pre-requirement on `id`, just leave it untouched pass to `resolve_id` directly. So it's not rolldown's responsibility to do anything with normalizing `\\` to `/`.
  - There is left thing is if `resolve_id` returns `/x/./index.js` and `/x/index.js`, should we consider them as the same thing? Following current no-touching behavior, they will be treated as different `id`.(I tend to keep this behavior if we can't come up with a best practice)

## For vite:

- If vite relies on normalizing `\\` to `/`, then vite should do it itself. However, considering the performance, we could have a builtin plugin to do it or move this behavior to some vite-only builtin plugin. In short, this behavior should be done by `rolldown-vite` instead of `rolldown`.

**Comment by sapphi-red** [comment]
I found a path normalization inconsistency between esbuild and rolldown (rollup), so linking here as a memo.
https://github.com/sapphi-red-repros/rolldown-esbuild-path-normalization

(No need to fix)
