### ISSUE TITLE
[Bug]: does not support browser field edge case

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2305]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-stheht?file=rolldown.config.mjs,pkg%2Fpackage.json
2. npm run build runs automatically.
3. `./dir` gets externalized automatically.

### What is expected?

No error happens and `./dir` resolve to `./file.js`.

### What is actually happening?

`./dir` gets externalized automatically and a warning is output.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@351d2c7 => 0.13.2
```

### Any additional comments?

See https://github.com/sapphi-red/package-json-browser-tests#:~:text=entry.js%3A%0A%20%20require(%27pkg%27)%0Anode_modules/pkg/package.json%3A%0A%20%20%7B%20%22main%22%3A%20%22main.js%22%2C%20%22browser%22%3A%20%7B%20%22./dir/index.js%22%3A%20%22./file%22%20%7D%20%7D%0Anode_modules/pkg/main.js%3A%0A%20%20require(%27./dir%27)%0Anode_modules/pkg/file.js%3A%0A%20%20input.works%20%3D%20true for compat with other bundlers. Only esbuild and Vite supports this case so probably fine to not support it.

Faced this while trying rolldown with Vite.

**Comment by hyf0** [comment]
No actions required, but FYI @Boshen cc.

**Comment by Boshen** [comment]
I find it really hard to reason about this example within the boundary of the resolution algorithm.

Given that there is no `./dir/` directory on disk, a request to `./dir` will bail any continuation logic for `./dir/index.js`, thus it should never hit the `"browser": { "./dir/index.js": "./file" }` case.

---

I remember trying to replicate similar behaviors in oxc-resolver but failed to do so. And I've spend countless hours on the browser field because the "specification" is not a real specification, all implementations decided to have their own interpretations of it.

I can try and implement edge cases if there are any npm packages that use a particular behavior. 

Feel free to reopen.
