### ISSUE TITLE
[Feature Request]: Make `require('external')` runnable in any execution context if possible

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2685]
### What problem does this feature solve?

When a CJS file `require`s an external module commonly builtin modules like `node:path`, `Error: Dynamic require of "*" is not supported` is thrown for the output bundle.

#### Reproduction steps
1. Open https://stackblitz.com/edit/github-xv4yss-2sb9fe?file=rolldown.config.mjs,src%2Fentry.js,src%2Fa.cjs
2. `npm i` runs automatically
3. `npm run build` runs automatically
4. run `node dist/entry.js`. It errors with `Error: Dynamic require of "node:path" is not supported`.
5. run `npm run build:up` to use rollup
6. run `node dist/entry.js`. It runs successfully.

#### Workarounds

I'm setting
```js
banner: "import { createRequire as ___createRequire } from 'module'; const require = ___createRequire(import.meta.url);",
```
like when I encounter https://github.com/evanw/esbuild/issues/1921.

### What does the proposed API look like?

For `platform: 'node'`, it should be safe to use `import module from 'node:module'; const require = module.createRequire(import.meta.url)` for it.
For other `platform`s, I guess converting `require` into `import` is what users want in most cases. This may lead to crash in some cases due to incompatibility of `module.exports` / `export *`, so probably we need an option to control the interop code like [`requireReturnsDefault` option in @rollup/plugin-commonjs](https://github.com/rollup/plugins/blob/master/packages/commonjs/README.md#requirereturnsdefault).

~~For any `platform`s, I guess the node builtins can be treated as it's safe to convert `require` into `import` even if it's externalized.~~ probably this isn't safe due to hoisting?

**Comment by sapphi-red** [comment]
This also happens when you try to bundle react for node.
https://stackblitz.com/edit/github-xv4yss-edjkwn?file=rolldown.config.mjs,src%2Fentry.js (same reproduction steps)

**Comment by hyf0** [comment]
I just test it https://stackblitz.com/edit/github-xv4yss-2sb9fe?file=rolldown.config.mjs,src%2Fentry.js,src%2Fa.cjs. It runs expectedly.

I guess the problem is that when you run `dist/entry.js`, node consider `dist/entry.js` as esm due to the root `package.json#type: "module"`. So there's no builtin `require` in it and that's why a error is throwed.

If you rename the `entry.js` to `entry.cjs`, everything works fine.

**Comment by hyf0** [comment]
```js
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, { get: (a, b) => (typeof require !== "undefined" ? require : a)[b] }) : x)(function(x) {
	if (typeof require !== "undefined") return require.apply(this, arguments);
	throw Error("Dynamic require of \"" + x + "\" is not supported");
});
```

`__require` is just a wrapper to provide friendly error message, it behave like the builtin `require` if the root scope have a `require`. So

```
banner: "import { createRequire as ___createRequire } from 'module'; const require = ___createRequire(import.meta.url);",

```
is also works.


> `__require` is just a wrapper to provide friendly error message

And I think this quite not achieve that goal, we might need to improve this function a little bit. Something like `Failed to require xxxx, because there's no require function. Are you running this file under node esm or browser?` @IWANABETHATGUY cc

**Comment by sapphi-red** [comment]
> I guess the problem is that when you run `dist/entry.js`, node consider `dist/entry.js` as esm due to the root `package.json#type: "module"`.

No, it's not. I'm trying to bundle it to ESM. I do expect Node to treat `dist/entry.js` as ESM.

**Comment by hyf0** [comment]
> > I guess the problem is that when you run `dist/entry.js`, node consider `dist/entry.js` as esm due to the root `package.json#type: "module"`.
> 
> No, it's not. I'm trying to bundle it to ESM. I expect Node to treat `dist/entry.js` as ESM.

If so, I guess the error is expected then. It's just message need to be polish to `Failed to require xxxx, because there's no require function. Are you running this file under node esm or browser?`.

I read the description again. Are you suggesting auto polyfill `require` for such situation?

**Comment by sapphi-red** [comment]
> I read the description again. Are you suggesting auto polyfill `require` for such situation?

Yes, for `platform: 'node'`.

Let me restate my propsal.

- For `platform: 'node'`
  - rolldown should inject `import { createRequire as ___createRequire } from 'module'; const require = ___createRequire(import.meta.url);` automatically.
  - rolldown should convert `const something = require('node:*')` into `import something from 'node:*'` as this would reduce the code size. Also might reduce the cases where the `createRequire` injection is needed.
    - This convertion should be safe.
- For other platforms (e.g. `platform: 'browser'`)
  - rolldown should add a option named `externalRequireAsImport` that controls whether the `require` to an external dependency can be converted to `import`. The option defaults to `true`. Converting `import` into `require` is not safe, but that's how other bundles work and I guess users will expect. It may be a good idea to add a warning that explains that if the option was not set explicitly.
    - `true`: convert all `require` into `import`
    - `[depName]`: convert `require(depName)` into `import`
    - `[]`: does not convert any `require`s

**Comment by hyf0** [comment]
Let me try to clarify some points:

- With `platform: node` and `format: esm`, should rollldown inject polyfill if there is `require('external')` statement?

This is already could be done in user-land

```js
// polyfill.js
import { createRequire as ___createRequire } from 'module';
export const require = ___createRequire(import.meta.url);

// rolldown.config.js
export default defineConfig({
  inject: {
    // This could even be a data url.
    'require': [path.resolve(import.meta.dirname, './polyfill.js'), 'require']
  }
})
```

- With other platform,  should rolldown convert `console.log(require('external'))` to `import ext from 'external'; console.log(ext)`?

Esbuild rejects to do this due to `require` and `import` have different semantic, can't replace one with the other.

I'm in favor of esbuild's point. So I don't think rolldown should support natively.

There's argument saying that just converting `require` to static `import`. I don't care about the semantic, it works on my case and that's fine.

I'm quite approve this too. Get things done is users' first requirement.

We could meet users' need with improving our guidance. Like

```
throw Error("Dynamic require of \"" + x + "\" is not supported. See ... for details");
```

And write a detail guidance on how he should do in `...`, such as workaround mentioned in https://github.com/evanw/esbuild/issues/566.

I prefer to not add option to do this natively, it's not a suggested pattern and shouldn't be encouraged.

**Comment by yyx990803** [comment]
What I think:

1. Auto injection of `createRequire()` when `platform=node & format=esm` is safe and makes things just work - we should do that.
2. Converting `require` to `import` is fundamentally unsafe and IMO we should not do that.
   - We can make assumptions about know Node built-ins, but if it's a 3rd party external then there could be many issues (e.g. the 3rd part dep is CJS and fails `cjs-module-lexer`'s re-export checks)
   - It may also resolve to different files due to exports conditions, leading to potential dual-module hazard.
   - When platform is `browser`, sometimes users may want non-top-level, or conditional `require('external')` calls to be preserved as-is, expecting them to be never called at runtime. Converting such require calls to static imports will cause it to fail on load.

**Comment by hyf0** [comment]
Planned, but needs to investigate the implementation.

**Comment by datner** [comment]
+1 what @/yyx990803 said
I had expected that using it in node would Just Work ™ for node builtins when targeting nodes preferred format, I was caught off guard by this.
It would be lovely to tackle the `node:*` separately from other dynamic imports so that a fault or complication in the latter won't impact the former (plus it'll ship faster 😛 )
