### ISSUE TITLE
[Bug]: rolldown:runtime: es5 umd not working due to non-es5 code being injected

### ISSUE THREAD

**Issue by kmalakoff** [rolldown/rolldown#3243]
### Reproduction link or steps

Use a tsconfig file with es5 as a target and format umd. 

### What is expected?

It should only inject es5 compatible code

### What is actually happening?

It's injecting es6 runtime. See the arrow functions:

```
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
		key = keys[i];
		if (!__hasOwnProp.call(to, key) && key !== except) __defProp(to, key, {
			get: ((k) => from[k]).bind(null, key),
			enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
		});
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));

```

### System Info

```Shell
System:
    OS: macOS 15.2
    CPU: (14) arm64 Apple M4 Pro
    Memory: 4.21 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    npm: 11.0.0 - /usr/local/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.2
```

### Any additional comments?

I'm excited to use rolldown! Please expedite your es5 target testing

**Comment by underfin** [comment]
Here has two things need to do.
- ~~The rolldown `target` option is not enable for all files~~
- The `target` is not binding to js side.
- respect the fields at `tsconfig.json`

**Comment by hyf0** [comment]
- The team has few thoughts on es5 support. But the current conclusion is there will be no official support on transforming output to es5.
  - There might will be a third-party plugin to transform the the bundled output to es5.
- Rolldown doesn't aware of `tsconfig.json` and we gonna keep this behavior.
  - Thing might be different for rolldown-vite(vite that's powered-by-rolldown. rolldown-vite will detect `tsconfig.json` automatically.

**Comment by kmalakoff** [comment]
> Rolldown doesn't aware of tsconfig.json and we gonna keep this behavior

I'm using my a rollup plugin to convert to es5 that respects the tsconfig file, but the shims are es6. It seems a waste to transpile twice, but okay

**Comment by IWANABETHATGUY** [comment]
> > Rolldown doesn't aware of tsconfig.json and we gonna keep this behavior
> 
> I'm using my a rollup plugin to convert to es5 that respects the tsconfig file, but the shims are es6. It seems a waste to transpile twice, but okay

Currently our upstream transpiler `oxc` don't have enough bandwidth to support lowering to `es5` and if you want to lower to `es5` you could use `swc` to lower it first , maybe we should give a warning when target is set to `es5` in tsconfig.

**Comment by overlookmotel** [comment]
Hi. I'm one of Oxc team. It's true that downlevelling to ES5 is out of scope for us for the forseeable future. It'd be a *massive* task. We are currently putting the finishing touches to ES6 downlevelling, and that has been a long road, because we're aiming for an implementation which is (a) very performant, and (b) more correct than existing transform implementations (SWC, ESBuild etc) in all the weird corner cases of JS. We are prioritizing quality of implementation over expanding the scope to ES5.

But...

Can I check I've understood your issue correctly? I *think* what you're saying is:

* You are already using a plugin to downlevel to ES5.
* So you *don't* need Rolldown/Oxc to perform ES5 downlevelling.
* The problem is that Rolldown is injecting *new* code (helper methods) which include ES6 syntax.

If I've understood right, that's a slightly different problem.

I don't know Rolldown well enough to say if this is possible but:

1. *Maybe* Rolldown could provide ES5-compatible versions of the helper methods when target is ES5 (I don't know how many there are, so whether this is feasible or not). or
2. Can you use a later hook to run your external ES5 downlevelling on *outputs* instead of inputs? That would avoid having to run ES5 transform twice.

**Comment by IWANABETHATGUY** [comment]
> Hi. I'm one of Oxc team. It's true that downlevelling to ES5 is out of scope for us for the forseeable future. It'd be a _massive_ task. We are currently putting the finishing touches to ES6 downlevelling, and that has been a long road, because we're aiming for an implementation which is (a) very performant, and (b) more correct than existing transform implementations (SWC, ESBuild etc) in all the weird corner cases of JS. We are prioritizing quality of implementation over expanding the scope to ES5.
> 
> But...
> 
> Can I check I've understood your issue correctly? I _think_ what you're saying is:
> 
> * You are already using a plugin to downlevel to ES5.
> * So you _don't_ need Rolldown/Oxc to perform ES5 downlevelling.
> * The problem is that Rolldown is injecting _new_ code (helper methods) which include ES6 syntax.
> 
> If I've understood right, that's a slightly different problem.
> 
> I don't know Rolldown well enough to say if this is possible but:
> 
> 1. _Maybe_ Rolldown could provide ES5-compatible versions of the helper methods when target is ES5 (I don't know how many there are, so whether this is feasible or not). or
> 2. Can you use a later hook to run your external ES5 downlevelling on _outputs_ instead of inputs? That would avoid having to run ES5 transform twice.

Welcome back!

**Comment by kmalakoff** [comment]
@overlookmotel I appreciate this follow up. Yes, I'm already down-levelling to ES5 using an swc rollup plugin. 

> The problem is that Rolldown is injecting new code (helper methods) which include ES6 syntax

Yes, the helper methods only are the problem. 

I was assuming this was a simple fix, eg. get rid of features like `() =>` in the helper methods.

**Comment by overlookmotel** [comment]
Thanks for coming back. OK, glad I understood correctly.

Have you tried my 2nd suggestion - do your ES5 transform on outputs *after* the helper methods have been injected, rather than before?

I doubt Rolldown would want to change the helper methods to ES5 because ES6 is fine for most users and it's more compact (so smaller bundles).

Rolldown guys may be able to answer on whether it's feasible to provide *alternative* helper methods which avoid ES6 syntax when target is ES5. I don't know enough about Rolldown to say whether that'd be workable or not. But if there's a simple workaround - run SWC *after* helpers are injected - then likely that's the best solution, and it makes providing ES5-compatible helper methods unnecessary.

If you'd be able to try that and report back, it'd be helpful.

**Comment by kmalakoff** [comment]
@overlookmotel Thank you for the suggestion. I've moved my transpiling to ES5 outside of rolldown and it works. I appreciate the suggestion!

**Comment by e111077** [comment]
@overlookmotel Do you happen to have an issue / milestone / tracker published somewhere regarding ES6 donwleveling support in OXC? Or if it's already merged, do you know what published version we could expect it?

**Comment by overlookmotel** [comment]
ES6 downlevelling is complete and has been released. It's alpha at present, so probably some bugs remaining in edge cases, but we're working on hardening it up. We are currently working on transforming decorators. Tracking issue: https://github.com/oxc-project/oxc/issues/4047

If any further Qs about Oxc, please feel free to raise an issue in Oxc repo, or reach out on our [Discord](https://discord.gg/9uXCAwqQZW).
