### ISSUE TITLE
Should rendering runtime module in snapshot testing?

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#390]
Because the runtime code is larger, snapshotted it is difficult to review, we need to deal it.

The original discuss at https://github.com/rolldown-rs/rolldown/pull/375

**Comment by hyf0** [comment]
I look up how esbuild did and it just omit the runtime code. We can't follow it due to we need to execute the build output after bundling.

In the test environment, https://github.com/rolldown-rs/rolldown/commit/5e7491e9dd27a9f930baea7f2cd786798d91ecef will always pretend that the runtime module belong to a facade entry, which makes him always generate the standalone chunk for the runtime module.

This also test the tree shaking step. `import ... from '$runtime#'` will easily tell us if we import runtime functions on demand.

Beyond that, the commit also ensures the runtime chunk is created on demand.

I consider that the current solution is in a balanced position, so the issue was closed.
